"""
Django settings for Attenova project.

Generated by 'django-admin startproject' using Django 5.2.6.

All secrets and environment-specific values are read from environment
variables. Use .env for local development (see .env.example).
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root when present (e.g. local development)
load_dotenv(BASE_DIR / ".env")
load_dotenv()


def env_bool(key: str, default: bool = False) -> bool:
    """Return True if env var is one of 'true', '1', 'yes' (case-insensitive)."""
    val = os.environ.get(key, "").lower()
    if val in ("true", "1", "yes"):
        return True
    if val in ("false", "0", "no", ""):
        return default
    return default


def env_list(key: str, default: list[str] | None = None, sep: str = ",") -> list[str]:
    """Return list of non-empty stripped strings from env var."""
    raw = os.environ.get(key, "")
    if not raw.strip():
        return default or []
    return [s.strip() for s in raw.split(sep) if s.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("Set the SECRET_KEY environment variable (e.g. in .env).")

DEBUG = env_bool("DEBUG", default=True)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=[])

# CORS: set CORS_ALLOWED_ORIGINS to your frontend URL(s). When DEBUG, default includes localhost:8080.
_cors_origins = env_list("CORS_ALLOWED_ORIGINS") or (
    ["http://localhost:8080", "http://127.0.0.1:8080"] if DEBUG else []
)
CORS_ALLOWED_ORIGINS = _cors_origins
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = True

# CSRF: allow cross-origin POST from frontend (Origin header check). Set same as CORS origins.
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS") or (
    ["http://localhost:8080", "http://127.0.0.1:8080"] if DEBUG else []
)


# Application definition

INSTALLED_APPS = [
    "django_crontab",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Attenova apps
    "Organization",
    "Users",
    "Employee",
    "Shifts",
    "Biometric",
    "Attendance",
    "Reports",
    "dashboard",
    "Notifications",
    "marketing",
]

# Custom user model (email-based, org-scoped roles)
AUTH_USER_MODEL = "Users.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Attenova.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Attenova.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_default_engine = os.environ.get("ATTENOVA_DB_ENGINE", "sqlite3").lower()

DATABASES = {}

if _default_engine == "sqlite3":
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / os.environ.get("SQLITE_DB_NAME", "db.sqlite3"),
    }
elif _default_engine == "postgresql":
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("ATTENOVA_DB_NAME", os.environ.get("DEFAULT_DB_NAME", "attenova_staging")),
        "USER": os.environ.get("ATTENOVA_DB_USER", os.environ.get("DEFAULT_DB_USER", "")),
        "PASSWORD": os.environ.get("ATTENOVA_DB_PASSWORD", os.environ.get("DEFAULT_DB_PASSWORD", "")),
        "HOST": os.environ.get("ATTENOVA_DB_HOST", os.environ.get("DEFAULT_DB_HOST", "localhost")),
        "PORT": os.environ.get("ATTENOVA_DB_PORT", os.environ.get("DEFAULT_DB_PORT", "5432")),
        "CONN_MAX_AGE": int(os.environ.get("ATTENOVA_DB_CONN_MAX_AGE", os.environ.get("DEFAULT_DB_CONN_MAX_AGE", "0"))),
        "OPTIONS": {},
    }
else:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("ATTENOVA_DB_NAME", os.environ.get("DEFAULT_DB_NAME", "attenova")),
        "USER": os.environ.get("ATTENOVA_DB_USER", os.environ.get("DEFAULT_DB_USER", "")),
        "PASSWORD": os.environ.get("ATTENOVA_DB_PASSWORD", os.environ.get("DEFAULT_DB_PASSWORD", "")),
        "HOST": os.environ.get("ATTENOVA_DB_HOST", os.environ.get("DEFAULT_DB_HOST", "localhost")),
        "PORT": os.environ.get("ATTENOVA_DB_PORT", os.environ.get("DEFAULT_DB_PORT", "3306")),
        "OPTIONS": {"charset": "utf8mb4"},
    }

# ESSL biometric DB: only added when ESSL_DB_NAME is set
if os.environ.get("ESSL_DB_NAME"):
    DATABASES["essl_db"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["ESSL_DB_NAME"],
        "USER": os.environ.get("ESSL_DB_USER", ""),
        "PASSWORD": os.environ.get("ESSL_DB_PASSWORD", ""),
        "HOST": os.environ.get("ESSL_DB_HOST", "localhost"),
        "PORT": os.environ.get("ESSL_DB_PORT", "3306"),
        "CONN_MAX_AGE": int(os.environ.get("ESSL_DB_CONN_MAX_AGE", "30")),
        "OPTIONS": {"charset": "utf8mb4"},
    }

# ESSL biometric sync (tunable via env)
ESSL_DEVICE_LOGS_TABLE = os.environ.get("ESSL_DEVICE_LOGS_TABLE", "DeviceLogs_2_2026")
ESSL_SYNC_BATCH_SIZE = int(os.environ.get("ESSL_SYNC_BATCH_SIZE", "5000"))
ESSL_SYNC_MAX_BATCHES = int(os.environ.get("ESSL_SYNC_MAX_BATCHES", "20"))

# Cron: run attendance sync every 5 minutes; daily report at 1 AM
CRONJOBS = [
    ("*/5 * * * *", "Biometric.cron.run_attendance_sync"),
    ("0 1 * * *", "django.core.management.call_command", ["send_daily_attendance_report"]),
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", "en-us")

TIME_ZONE = os.environ.get("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Email (for daily attendance report, notifications, etc.)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Attenova <noreply@attenova.local>")

# Landing page “Book a demo” submissions (notification recipient).
DEMO_BOOKING_INBOX = os.environ.get(
    "DEMO_BOOKING_INBOX",
    "akashyadav181198@gmail.com",
).strip()

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "static/")
MEDIA_URL = os.environ.get("MEDIA_URL", "media/")
MEDIA_ROOT = BASE_DIR / os.environ.get("MEDIA_ROOT", "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
