# Generated by Django 5.2.6 on 2026-04-30 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organization", "0007_office_managers_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="Organization.office",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "departments",
                "db_table": "department",
                "ordering": ["office", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("office", "name"), name="department_office_name_unique"
                    )
                ],
            },
        ),
    ]
