# Generated by Django 5.2.6 on 2026-04-30 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0011_employee_user"),
        ("Organization", "0008_department_and_employee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="Organization.department",
            ),
        ),
    ]
