# Generated by Django 5.2.6 on 2026-05-08 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0012_department_and_employee_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=16)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=64),
                ),
                ("current_address", models.TextField(blank=True)),
                ("permanent_address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True,
                        help_text="Optional display label; canonical site is office.",
                        max_length=255,
                    ),
                ),
                (
                    "employment_status_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ON_LEAVE — informational; does not replace is_active.",
                        max_length=64,
                    ),
                ),
                ("education_entries", models.JSONField(blank=True, default=list)),
                ("certifications", models.TextField(blank=True)),
                ("skills", models.TextField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_profile",
                        to="Employee.employee",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="HR-assigned reporting line (read-only for employee self-service API).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_managed_employees",
                        to="Employee.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee profile",
                "verbose_name_plural": "Employee profiles",
                "db_table": "employee_profile",
            },
        ),
    ]
