# Generated by Django 5.2.6 on 2026-03-08 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organization", "0007_office_managers_m2m"),
        ("Shifts", "0003_delete_employeeshift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("office",),
                name="shift_office_one_default_unique",
            ),
        ),
    ]
