# Generated by Django 5.2.6 on 2026-05-09 05:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Employee", "0013_employee_profile"),
        ("Organization", "0008_department_and_employee_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True)),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "total_allowed_days",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("allow_half_day", models.BooleanField(default=False)),
                ("allow_negative_balance", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="Organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_type",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_half_day", models.BooleanField(default=False)),
                (
                    "half_day_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIRST_HALF", "First half"),
                            ("SECOND_HALF", "Second half"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("total_days", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_note", models.TextField(blank=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="Employee.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_applications",
                        to="Leaves.leavetype",
                    ),
                ),
            ],
            options={
                "db_table": "leave_application",
                "ordering": ["-applied_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                (
                    "consumed_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="Employee.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_balances",
                        to="Leaves.leavetype",
                    ),
                ),
            ],
            options={
                "db_table": "employee_leave_balance",
            },
        ),
        migrations.AddIndex(
            model_name="leavetype",
            index=models.Index(
                fields=["organization", "is_active"],
                name="leave_type_organiz_332242_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="leave_type_org_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["employee", "status"], name="leave_appli_employe_66f7b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["employee", "start_date", "end_date"],
                name="leave_appli_employe_998af2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeleavebalance",
            index=models.Index(
                fields=["employee"], name="employee_le_employe_45cb3f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeleavebalance",
            constraint=models.UniqueConstraint(
                fields=("employee", "leave_type"), name="employee_leave_balance_unique"
            ),
        ),
    ]
