# Generated by Django 5.2.6 on 2026-05-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Leaves", "0002_leave_type_office_scoped"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="leavetype",
            new_name="leave_type_office__7eee49_idx",
            old_name="leave_type_office_active_idx",
        ),
    ]
