# Generated by Django 5.2.6 on 2026-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Biometric", "0006_biometricdevice_hardware_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biometricdevice",
            name="device_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in", "In"),
                    ("out", "Out"),
                    ("alternate_in_out", "Alternate In/Out"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="biometricdevice",
            name="device_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="biometricdevice",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("face", "Face"),
                    ("finger", "Finger"),
                    ("both", "Both"),
                    ("rfid", "RFID"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="biometricdevice",
            name="ip_address",
            field=models.CharField(
                blank=True, help_text="IPv4, IPv6, or hostname", max_length=45
            ),
        ),
        migrations.AlterField(
            model_name="biometricdevice",
            name="serial_number",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
