# Generated by Django 5.2.6 on 2026-03-08 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0004_attendanceregularization"),
        ("Organization", "0007_office_managers_m2m"),
        ("Shifts", "0003_delete_employeeshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="early_out_minutes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_regularized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="Organization.office",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="regularized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="Shifts.shift",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIOMETRIC", "Biometric"),
                    ("MANUAL", "Manual"),
                    ("REGULARIZATION", "Regularization"),
                ],
                default="BIOMETRIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
