# Generated by Django 5.2.6 on 2026-03-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0005_attendance_early_out_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punch_time", models.DateTimeField(db_index=True)),
                ("direction", models.CharField(max_length=8)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punches",
                        to="Attendance.attendance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance punch",
                "verbose_name_plural": "Attendance punches",
                "db_table": "attendance_punch",
                "ordering": ["attendance", "punch_time"],
            },
        ),
    ]
