# Generated by Django 5.2.6 on 2026-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0006_attendancepunch"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceregularization",
            name="previous_first_in",
            field=models.DateTimeField(
                blank=True,
                help_text="Snapshot from Attendance at request time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendanceregularization",
            name="previous_last_out",
            field=models.DateTimeField(
                blank=True,
                help_text="Snapshot from Attendance at request time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendanceregularization",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Present"),
                    ("A", "Absent"),
                    ("L", "Late"),
                    ("WO", "Weekly Off"),
                ],
                help_text="Snapshot from Attendance at request time",
                max_length=4,
                null=True,
            ),
        ),
    ]
